#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/* -----------------------------------------------------------------
 |  Register The Auto Loader
 | -----------------------------------------------------------------
 */

require __DIR__.'/vendor/autoload.php';

/**  @var \Illuminate\Contracts\Foundation\Application $app  */
$app = require_once __DIR__.'/bootstrap/app.php';

/* -----------------------------------------------------------------
 |  Run The Artisan Application
 | -----------------------------------------------------------------
 */

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/* -----------------------------------------------------------------
 |  Shutdown The Application
 | -----------------------------------------------------------------
 */

$kernel->terminate($input, $status);

exit($status);
